### ISSUE TITLE
Getting Neolink in Home Assistant working

### ISSUE THREAD

**Issue by Tobster77** [QuantumEntangledAndy/neolink#262]
**Describe the bug**
Instructions for Home Assistant are not fully clear

**To Reproduce**
1. Install Neolink as an Home Assistant Add-on
2. Add-on is running (according to log)
3. A Reolink device is auto-discovered in Home Assistant. But the connections fails
```Client connector error during login of host 192.168.178.65:443: Host 192.168.178.65:443: connection error: Cannot connect to host 192.168.178.65:443 ssl:default [Connect call failed ('192.168.178.65', 443)]```
To be honest, I am quite confused. 

- Should I connect to the camera itself (192.168.178.65) or the RTSP server provided (would that be localhost?)? 
- Which credentials are to be used? Those I defined in the neolink.toml, or those for the cam ("admin" and password)?
- How can I employ the abilities provided via MQTT? I have fundamental knowledge and the Mosquitto server running in Home Assistant for Zigbee2MQTT, but general instructions would be fine.

**Expected behavior**
What next to get the device showing up in Home Assistant?

**Versions**
NVR software: None, I would like to use the cam in Home Assistant
Neolink software: none
Reolink camera model and firmware: Reolink Argus 3 Ultra

Thank you!

**Comment by QuantumEntangledAndy** [comment]
The neolink add on is actually another project not directly linked to me so I'm not 100% sure. But I believe it works like this.

- The plug-in starts neolink in a docker.
- this means that it's not local host but whatever the docker address is
- the idea is that the neolink connects to the camera (as you can see in the log this works fine)
- ha should connect to neolink on the docker address in port 8554 (the rtsp server)

I'm not sure about your ssl error nor am I sure why your trying to connect on 443? Do you have any idea what ha is doing to try a connection on 443? What settings did you configure in ha?

For the mqtt you need to configure the neolink toml to connect to your mqtt server with the same credentials as your ha is so that they can talk to each other.

**Comment by Tobster77** [comment]
Thank you, I placed my request [here](https://github.com/dm82m/hassio-addons/issues/35)!

**Comment by Tobster77** [comment]
Okay, got this running!

Now I still fight with MQTT in Home Assistant:

I extended the features from
```
mqtt.discovery.topic = "homeassistant"
mqtt.discovery.features = ["floodlight"]
```
to
```
mqtt.discovery.topic = "homeassistant"
mqtt.discovery.features = ["floodlight", "camera", "led", "ir", "motion", "battery", "siren"]
```
but I still only get the floodlight switch in Home Assistant. Is the syntax correct?

**Comment by Tobster77** [comment]
After some hours of operation, the server crashes:

```
[2024-06-02T11:28:28Z INFO  neolink::utils] Kamera_Kellerausgang: Logging in
[2024-06-02T11:28:37Z INFO  neolink::utils] Kamera_Kellerausgang: Connected and logged in
[2024-06-02T11:28:37Z INFO  neolink::common::camthread] Kamera_Kellerausgang: Camera time is already set: 2024-06-02 13:28:37.0 -01:00:00
thread '<unnamed>' panicked at 'Could not build pipeline: channel closed', src/rtsp/gst/factory.rs:132:56
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
/run.sh: line 35:    14 Aborted                 (core dumped) neolink mqtt-rtsp --config /config/addons/neolink.toml
```
What can I do here?

**Comment by QuantumEntangledAndy** [comment]
Please send a complete log (including the version hash number thats right at the top)

**Comment by Tobster77** [comment]
Thanks. Here we go.... Unfortunately, the log is cut after a number of lines, so these are the last lines:
```
...
...
        Dropped connection
[2024-06-03T06:59:24Z INFO  neolink::common::camthread] Attempt reconnect in 50ms
[2024-06-03T06:59:24Z INFO  neolink::utils] Kamera_Kellerausgang: Connecting to camera at UID: xxxxxxxxxxxxx
[2024-06-03T06:59:24Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying local discovery
[2024-06-03T06:59:24Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying remote discovery
[2024-06-03T06:59:25Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying map discovery
[2024-06-03T06:59:25Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying relay discovery
[2024-06-03T06:59:26Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Remote discovery success xxxxxxxxxxxxx at 192.168.178.65:56125
[2024-06-03T06:59:26Z INFO  neolink::utils] Kamera_Kellerausgang: Logging in
[2024-06-03T06:59:31Z INFO  neolink::utils] Kamera_Kellerausgang: Connected and logged in
...
...
[2024-06-03T10:00:53Z INFO  neolink::utils] Kamera_Kellerausgang: Connected and logged in
[2024-06-03T10:00:53Z INFO  neolink::common::camthread] Kamera_Kellerausgang: Camera time is already set: 2024-06-03 12:00:52.0 -01:00:00
thread '<unnamed>' panicked at 'Could not build pipeline: channel closed', src/rtsp/gst/factory.rs:132:56
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
/run.sh: line 35:    13 Aborted                 (core dumped) neolink mqtt-rtsp --config /config/addons/neolink.toml
--- VERSIONS ---
add-on version: 0.0.9
neolink version: neolink 0.6.2
[2024-06-03T11:27:33Z INFO  neolink] Neolink e47a0d5734b0a06b53bd8d78be9ca2f6b8396480 release
neolink mode: dual
neolink log: info
ATTENTION: if you expected a newer Neolink version, please reinstall this Add-on!
--- Neolink ---
[2024-06-03T11:27:33Z INFO  neolink] Neolink e47a0d5734b0a06b53bd8d78be9ca2f6b8396480 release
[2024-06-03T11:27:34Z WARN  neolink::rtsp] Without a server certificate, usernames and passwords will be exchanged in plaintext!
[2024-06-03T11:27:34Z INFO  neolink::rtsp] Kamera_Kellerausgang: Rtsp Staring
[2024-06-03T11:27:34Z INFO  neolink::utils] Kamera_Kellerausgang: Connecting to camera at UID: xxxxxxxxxxxxx
[2024-06-03T11:27:34Z INFO  neolink::rtsp] Starting RTSP Server at 0.0.0.0:8554
[2024-06-03T11:27:34Z INFO  neolink::mqtt] Kamera_Kellerausgang: MQTT Staring
[2024-06-03T11:27:34Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying local discovery
[2024-06-03T11:27:35Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying remote discovery
[2024-06-03T11:27:36Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying map discovery
[2024-06-03T11:27:36Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying relay discovery
[2024-06-03T11:27:48Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Remote discovery success xxxxxxxxxxxxx at 192.168.178.65:56125
[2024-06-03T11:27:48Z INFO  neolink::utils] Kamera_Kellerausgang: Logging in
[2024-06-03T11:27:58Z WARN  neolink::common::camthread] Connection Lost: IO Error: Custom { kind: Other, error: DroppedConnection }
    
    Caused by:
        Dropped connection
[2024-06-03T11:27:58Z INFO  neolink::common::camthread] Attempt reconnect in 50ms
[2024-06-03T11:27:58Z INFO  neolink::utils] Kamera_Kellerausgang: Connecting to camera at UID: xxxxxxxxxxxxx
[2024-06-03T11:27:58Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying local discovery
[2024-06-03T11:28:00Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying remote discovery
[2024-06-03T11:28:00Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying map discovery
[2024-06-03T11:28:00Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying relay discovery
[2024-06-03T11:28:13Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Remote discovery success xxxxxxxxxxxxx at 192.168.178.65:56125
[2024-06-03T11:28:13Z INFO  neolink::utils] Kamera_Kellerausgang: Logging in
[2024-06-03T11:28:23Z WARN  neolink::common::camthread] Connection Lost: IO Error: Custom { kind: Other, error: DroppedConnection }
    
    Caused by:
        Dropped connection
[2024-06-03T11:28:23Z INFO  neolink::common::camthread] Attempt reconnect in 100ms
[2024-06-03T11:28:23Z INFO  neolink::utils] Kamera_Kellerausgang: Connecting to camera at UID: xxxxxxxxxxxxx
[2024-06-03T11:28:23Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying local discovery
[2024-06-03T11:28:24Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying remote discovery
[2024-06-03T11:28:25Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying map discovery
[2024-06-03T11:28:25Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying relay discovery
[2024-06-03T11:28:37Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Remote discovery success xxxxxxxxxxxxx at 192.168.178.65:56125
[2024-06-03T11:28:37Z INFO  neolink::utils] Kamera_Kellerausgang: Logging in
[2024-06-03T11:28:47Z WARN  neolink::common::camthread] Connection Lost: IO Error: Custom { kind: Other, error: DroppedConnection }
    
    Caused by:
        Dropped connection
[2024-06-03T11:28:47Z INFO  neolink::common::camthread] Attempt reconnect in 200ms
[2024-06-03T11:28:47Z INFO  neolink::utils] Kamera_Kellerausgang: Connecting to camera at UID: xxxxxxxxxxxxx
[2024-06-03T11:28:47Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying local discovery
[2024-06-03T11:28:50Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying remote discovery
[2024-06-03T11:28:51Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying map discovery
[2024-06-03T11:28:51Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying relay discovery
[2024-06-03T11:29:03Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Remote discovery success xxxxxxxxxxxxx at 192.168.178.65:56125
[2024-06-03T11:29:03Z INFO  neolink::utils] Kamera_Kellerausgang: Logging in
[2024-06-03T11:29:13Z WARN  neolink::common::camthread] Connection Lost: IO Error: Custom { kind: Other, error: DroppedConnection }
    
    Caused by:
        Dropped connection
[2024-06-03T11:29:13Z INFO  neolink::common::camthread] Attempt reconnect in 400ms
[2024-06-03T11:29:13Z INFO  neolink::utils] Kamera_Kellerausgang: Connecting to camera at UID: xxxxxxxxxxxxx 
[2024-06-03T11:29:13Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying local discovery
[2024-06-03T11:29:15Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying remote discovery
[2024-06-03T11:29:15Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying map discovery
[2024-06-03T11:29:15Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying relay discovery
[2024-06-03T11:29:28Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Remote discovery success xxxxxxxxxxxxx at 192.168.178.65:56125
[2024-06-03T11:29:28Z INFO  neolink::utils] Kamera_Kellerausgang: Logging in
[2024-06-03T11:29:38Z WARN  neolink::common::camthread] Connection Lost: IO Error: Custom { kind: Other, error: DroppedConnection }
    
    Caused by:
        Dropped connection
[2024-06-03T11:29:38Z INFO  neolink::common::camthread] Attempt reconnect in 800ms
[2024-06-03T11:29:38Z INFO  neolink::utils] Kamera_Kellerausgang: Connecting to camera at UID: 95270006TIZ21QI9
[2024-06-03T11:29:38Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying local discovery
[2024-06-03T11:29:40Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying remote discovery
[2024-06-03T11:29:41Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying map discovery
[2024-06-03T11:29:41Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying relay discovery
[2024-06-03T11:29:42Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Remote discovery success xxxxxxxxxxxxx at 192.168.178.65:56125
[2024-06-03T11:29:42Z INFO  neolink::utils] Kamera_Kellerausgang: Logging in
[2024-06-03T11:29:51Z INFO  neolink::utils] Kamera_Kellerausgang: Connected and logged in
[2024-06-03T11:29:52Z INFO  neolink::common::camthread] Kamera_Kellerausgang: Camera time is already set: 2024-06-03 13:29:51.0 -01:00:00
[2024-06-03T11:29:53Z INFO  neolink::common::neocam] Kamera_Kellerausgang: Model Argus 3 Ultra
[2024-06-03T11:29:53Z INFO  neolink::common::neocam] Kamera_Kellerausgang: Firmware Version v3.0.0.2355_23062001
[2024-06-03T11:29:55Z INFO  neolink::rtsp] Kamera_Kellerausgang: Avaliable at /Kamera_Kellerausgang/main, /Kamera_Kellerausgang/Main, /Kamera_Kellerausgang/mainStream, /Kamera_Kellerausgang/MainStream, /Kamera_Kellerausgang/Mainstream, /Kamera_Kellerausgang/mainstream, /Kamera_Kellerausgang
[2024-06-03T11:29:55Z INFO  neolink::rtsp] Kamera_Kellerausgang: Activating Client
[2024-06-03T11:29:55Z INFO  neolink::rtsp] Kamera_Kellerausgang: Pausing Client
[2024-06-03T11:29:56Z INFO  neolink::rtsp] Kamera_Kellerausgang: Activating Client
[2024-06-03T11:29:56Z INFO  neolink::rtsp] Kamera_Kellerausgang: Pausing Client
[2024-06-03T11:29:56Z INFO  neolink::rtsp] Kamera_Kellerausgang: Avaliable at /Kamera_Kellerausgang/sub, /Kamera_Kellerausgang/Sub, /Kamera_Kellerausgang/subStream, /Kamera_Kellerausgang/SubStream, /Kamera_Kellerausgang/Substream, /Kamera_Kellerausgang/substream
[2024-06-03T11:29:59Z WARN  neolink_core::bc_protocol::snap] Snap did not recieve expected number of byes
[2024-06-03T11:30:35Z WARN  neolink_core::bc_protocol::snap] Snap did not recieve expected number of byes
[2024-06-03T11:30:47Z WARN  neolink_core::bc_protocol::snap] Snap did not recieve expected number of byes
[2024-06-03T11:31:10Z WARN  neolink_core::bc_protocol::snap] Snap did not recieve expected number of byes
[2024-06-03T11:31:24Z WARN  neolink_core::bc_protocol::snap] Snap did not recieve expected number of byes
...
```

I then rebooted the cam and the add-on to get a connection again...

**Comment by Tobster77** [comment]
Does this help?

**Comment by Tobster77** [comment]
Is there anything I can provide? Thanks.

**Comment by Tobster77** [comment]
Okay, may I assume that there is no simple solution at hand? Then I maybe skip the battery-driven cam and Neolink and better pay for a natively supported PoE model?

**Comment by QuantumEntangledAndy** [comment]
Sorry its not something obvious for me to just fix and I don't really have the time to solve it. The connecting being dropped is a low level thing where one of the connections TCP/UDP or the channels between threads is being closed. Theres a lot of places where it can happen and unless I can replicate it on my own and have a few days to work on it then I won't be able to fix it
